### ISSUE TITLE
TypeScript compatibility checklist

### ISSUE THREAD

**Issue by cainlevy** [nteract/semiotic#529]
I've opened a couple of issues from attempting to use Semiotic v2 in TypeScript, then belatedly realized there may be enough to warrant a single thread and spare you the spam.

* [x] add types to the `package.json` [#527]
* [x] fix types from `createResponsiveFrame` [#528]
* [x] track down the missing `src/components/types/ordinalTypes` file
* [x] resolve props that have defaults but are marked non-optional (e.g. `<XYFrame annotations />` and `<ResponsiveFrame debounce />`)
* [x] take a first pass at specifying the ~30 missing (aka `any`) types
* [ ] require types to pass during CI

I'd be happy to contribute towards this progress. Semiotic's approach to data visualization resonates with me, but I'm having trouble getting started with these issues.

**Comment by emeeks** [comment]
Sorry for the hassle but I really appreciate you systematically hitting it like this. I'll try to resolve these.

**Comment by emeeks** [comment]
Take a look at rc6 and tell me how that works for you. I got rid of a lot of the anys and I think I got responsive frame types working and modified the tsconfig entry point to point at lib instead of dist, so I think we're in much better shape but would love to hear what's still missing.

**Comment by emeeks** [comment]
Okay, rc6 had a bit of a mess to it, try rc7 it seems much more stable.

**Comment by willingc** [comment]
Looks like this file resurfaced earlier this year: https://github.com/nteract/semiotic/blob/main/src/components/types/ordinalTypes.ts

**Comment by willingc** [comment]
Closing this and tracking last action item in issue #576.
